config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/intro", to: "pages#intro"

  get "/dashboard", to: "dashboards#index"

  resources :castles, only: %i[index new show create edit update] do
    resources :favorites, only: %i[create update destroy]
    resources :reviews, only: %i[create]
    resources :bookings, only: :create do
      resources :payments, only: :new
    end
  end

  resources :reviews, only: %i[edit update destroy]
  resources :castles, only: :destroy
  resources :bookings, only: %i[show destroy]

  get "/castles/user/:id", to: "castles#index_by_user", as: "user_index"
  get "/castles/:id/fullscreen", to: "castles#full_screen", as: "full_screen"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-controller="timeout">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-controller="timeout">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="footer-links">
    <li>réalisé par Jacques-Antoine de Cugnac</li>
    <li><a href="mailto:ja.decugnac@outlook.com"><i class="fa-regular fa-envelope"></i></a></li>
    <li><a href="https://github.com/jadc96" target="_blank"><i class="fab fa-github"></i></a></li>
    <li><a href="https://www.linkedin.com/in/jacques-antoine-de-cugnac/" target="_blank"><i class="fab fa-linkedin"></i></a></li>
    <li><a href="mailto:ja.decugnac@outlook.com">Me contacter</a></li>
  </ul>
</div>

app/views/shared/_fullscreen.html.erb
<div class="total" id="qqch" data-controller="fullscreen">
  <div class="gallery">
    <p><%= link_to "Retour", castle_path(@castle.id) %></p>
    <% i = 0 %>

    <% @castle.photos.each do |p| %>

      <div class="small-picture" data-action="click->fullscreen#setBackground">
        <%= cl_image_tag p.key, height: 50, width: 50, crop: :fill, id: "img#{i}", class: "#{p.url}" %>
        <% i += 1 %>
      </div>

    <% end %>

  </div>

  <div class="full-screen-img">
    <img data-fullscreen-target="img" src="<%= @castle.photos.first.url %>" alt="">
  </div>
</div>

app/views/shared/_home-banner.html.erb
<div class="banner">
  <div class="big-img">
    <h1>CASTRVM</h1>
    <p>Goûtez à la vie de château</p>
    <%= link_to intro_path do %>
      <img class="enter" src="https://res.cloudinary.com/dvz6du0ze/image/upload/v1705775826/castrvm/lmmu4o46qbbkbekuxexh.png" alt="">
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light border">

    <div class="nav-links">
      <%= link_to intro_path, class: "navbar-brand" do %>
        <img class="house" src="https://res.cloudinary.com/dvz6du0ze/image/upload/v1705775826/castrvm/lmmu4o46qbbkbekuxexh.png" alt="">
      <% end %>

      <%= link_to "Toutes les annonces", castles_path %>
    </div>

    <%= render "shared/searchbar" %>

    <% if user_signed_in? %>
      <div class="links">
        <button class="my-profile"><%= link_to "Mon profil", "/dashboard" %></button>
      </div>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fas fa-user-circle"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_castles.html.erb
<div class="navbar navbar-expand-sm navbar-light border">
    <div class="nav-links">
      <%= link_to intro_path, class: "navbar-brand" do %>
        <img class="house" src="https://res.cloudinary.com/dvz6du0ze/image/upload/v1705775826/castrvm/lmmu4o46qbbkbekuxexh.png" alt="">
      <% end %>

      <%= link_to "Accueil", intro_path %>
    </div>

    <% if user_signed_in? %>
      <div class="links">
        <button class="my-profile"><%= link_to "Mon profil", "/dashboard" %></button>
      </div>
    <% else %>
      <%= link_to new_user_session_path do %>
        <i class="fas fa-user-circle"></i>
      <% end %>
    <% end %>
</div>

app/views/shared/_searchbar.html.erb
<div class="border d-flex p-2">
  <form action="/castles" method="get">
    <input type="text" name="search" class="border-0 border-secondary bg-transparent placeholder-padding" placeholder='Votre recherche'/>
    <button name="button" type="submit" class="border-0 bg-transparent">
      <i class="fas fa-search"></i>
    </button>
  </form>
</div>