config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/intro", to: "pages#intro"

  get "/dashboard", to: "dashboards#index"

  resources :castles, only: %i[index new show create edit update] do
    resources :favorites, only: %i[create update destroy]
    resources :reviews, only: %i[create]
    resources :bookings, only: :create do
      resources :payments, only: :new
    end
  end

  resources :reviews, only: %i[edit update destroy]
  resources :castles, only: :destroy
  resources :bookings, only: %i[show destroy]

  get "/castles/user/:id", to: "castles#index_by_user", as: "user_index"
  get "/castles/:id/fullscreen", to: "castles#full_screen", as: "full_screen"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @dashboard = policy_scope(Booking)
  end
end

app/views/dashboards/index.html.erb
<br>
<p class="quit"><%= link_to "Me déconnecter", destroy_user_session_path, data: {turbo_method: :delete} %><i class="fa-solid fa-right-from-bracket"></i></p>

<% if params[:favorites] == "true"  %>

  <div class="tabs">
    <h1 class="tab"><%= link_to "Mes réservations", dashboard_path %></h1>
    <h1 class="tab" style="background-color: rgb(243, 243, 243);"><%= link_to "Mes favoris", dashboard_path(favorites: true) %></h1>
  </div>

  <% if current_user.favorites.empty? %>
    <div class="fav-container border"><h4>Vous n'avez pas de favoris</h4></div>
  <% else %>
    <div class="row border fav-container">
      <% current_user.favorites.each do |f| %>
        <div class="col-4">

          <% castle = Castle.where(id: f.castle_id).first %>
          <a href="<%= castle_path(castle.id)%>">
            <div class="card-product">
              <%= cl_image_tag castle.photos.first.key, height: 300, width: 400, crop: :fill %>

              <div class="card-product-infos">
                <% if castle.reviews.empty? %>
                  <div class="rate">
                    <h2><%= castle.name %></h2>
                    <p>pas de note</p>
                  </div>
                <% else %>
                  <div class="rate">
                    <% reviews = castle.reviews.map do |r| p r.rating end %>
                    <h2 class="title-rate-card"><%= castle.name %></h2>
                    <p><%= reviews.sum / reviews.length %> /5</p>
                  </div>
                <% end %>
                <p><%= castle.department %></p>
                <p><%= castle.price_per_day %>€ / jour</p>
              </div>

            </div>
          </a>
        </div>

      <% end %>
    </div>
  <% end %>



<% else %>

  <div class="tabs">
    <h1 class="tab" style="background-color: rgb(243, 243, 243);"><%= link_to "Mes réservations", dashboard_path %></h1>
    <h1 class="tab"><%= link_to "Mes favoris", dashboard_path(favorites: true) %></h1>
  </div>

  <div class="container-dashboard d-flex row card-radius">
    <div class="col align-self-center row align-items-start my-3">

    <!-- pending bookings-->

      <div class= "col text-center">
        <span class="pending-status mt-2">EN ATTENTE...</span>
        <% pending_bookings = Booking.where(user_id: current_user.id).where(status: "pending") %>

        <% if pending_bookings.empty? %>
          <p class="no-booking">Vous n'avez pas de réservations en attente.</p>
        <% else %>
          <div class="cards-2">
            <% Booking.where(user_id: current_user.id).where(status: "pending").each do |b| %></p>
              <div class="card-product-2">
                <%= cl_image_tag b.castle.photos.first.key %>
                <div class="card-product-2-infos">
                  <div class="card-product-2-details">
                    <h5><strong><%= link_to b.castle.name, new_castle_booking_payment_path(b.castle_id, b.id) %></strong></h5>
                    <p> Prix par jour : <%= b.castle.price_per_day %> €</p>
                    <p> Prix total : <%= b.total_price %> €</p>
                    <p> Dates : <%= b.start_date.strftime('%d/%m/%Y') %> - <%= b.end_date.strftime('%d/%m/%Y') %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <!-- accepted bookings -->

      <div class= "col status text-center">
        <span class="accepted-status mt-2"><i class="fa-solid fa-check"></i>PAYÉES</span>
        <% paid_bookings = Booking.where(user_id: current_user.id).where(status: "paid") %>
        <% if paid_bookings.empty? %>
          <p class="no-booking">Vous n'avez pas encore de réservation payée.</p>
        <% else %>
          <div class="cards-2">
            <% Booking.where(user_id: current_user.id).where(status: "paid").each do |b| %></p>
              <div class="card-product-2">
                <%= cl_image_tag b.castle.photos.first.key %>
                <div class="card-product-2-infos">
                  <div class="card-product-2-details">
                    <h5><strong><%= link_to b.castle.name, booking_path(b) %></strong></h5>
                    <p> Prix par jour : <%= b.castle.price_per_day %> €</p>
                    <p> Prix total : <%= b.total_price %> €</p>
                    <p> Dates : <%= b.start_date.strftime('%d/%m/%Y') %> - <%= b.end_date.strftime('%d/%m/%Y') %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% end %>