config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "/intro", to: "pages#intro"

  get "/dashboard", to: "dashboards#index"

  resources :castles, only: %i[index new show create edit update] do
    resources :favorites, only: %i[create update destroy]
    resources :reviews, only: %i[create]
    resources :bookings, only: :create do
      resources :payments, only: :new
    end
  end

  resources :reviews, only: %i[edit update destroy]
  resources :castles, only: :destroy
  resources :bookings, only: %i[show destroy]

  get "/castles/user/:id", to: "castles#index_by_user", as: "user_index"
  get "/castles/:id/fullscreen", to: "castles#full_screen", as: "full_screen"

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/castle.rb
class Castle < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :subtitle, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :department, presence: true
  validates :price_per_day, presence: true
  validates :number_of_bed, presence: true
  validates :photos, presence: true

  has_many_attached :photos

  geocoded_by :address

  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  before_action :set_castle, only: %i[show full_screen edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show full_screen]

  def index
    @castles = policy_scope(Castle)
    @map = false
    if params[:search].present?
      sql_query = "castles.name ILIKE :query OR castles.department ILIKE :query OR castles.address ILIKE :query"
      @castles = Castle.where(sql_query, query: "%#{params[:search]}%")
    end
    @markers = @castles.geocoded.map do |castle|
      {
        lat: castle.latitude,
        lng: castle.longitude,
        info_window: render_to_string(partial: "info_window", locals: { castle: castle })
      }
    end
  end

  def index_by_user
    @castles = Castle.where(user_id: params[:id])
    authorize @castles
  end

  def show
    authorize @castle
    @markers = [
      {
        lat: @castle.latitude,
        lng: @castle.longitude,
        info_window: render_to_string(partial: "info_window", locals: { castle: @castle })
      },
      {
        lat: @castle.latitude,
        lng: @castle.longitude,
        info_window: render_to_string(partial: "info_window", locals: { castle: @castle })
        }]
    @booking = Booking.new
    @review = Review.new
  end

  def full_screen
    authorize @castle
  end

  def new
    @castle = Castle.new
    authorize @castle
  end

  def create
    @castle = Castle.new(params_castle)
    authorize @castle
    @castle.user = current_user
    if @castle.save
      redirect_to castle_path(@castle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @castle
  end

  def update
    authorize @castle
    if @castle.update(params_castle)
      redirect_to castle_path(@castle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @castle
    @castle.destroy
    redirect_to castles_path, status: :see_other
  end

  private

  def set_castle
    @castle = Castle.find(params[:id])
  end

  def params_castle
    params.require(:castle).permit(:name, :subtitle, :description, :address, :department, :price_per_day, :number_of_bed, :smokers_welcome, :animals_welcome, :wifi, photos: [])
  end
end

app/views/castles/_form.html.erb
<div class="content-create-castle">
  <div class="create-castle">
  <h2>Créez votre annonce</h2>
  <%= simple_form_for @castle do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.input :subtitle, label: "Une petite phrase d'accroche" %>
    <%= f.input :department,
              collection: ["01 - Ain","02 - Aisne","03 - Allier","04 - Alpes-de-Haute-Provence","05 - Hautes-Alpes","06 - Alpes-Maritimes","07 - Ardèche","08 - Ardennes","09 - Ariège","10 - Aube","11 - Aude","12 - Aveyron","13 - Bouches-du-Rhône","14 - Calvados","15 - Cantal","16 - Charente","17 - Charente-Maritime","18 - Cher","19 - Corrèze","2A - Corse-du-Sud","2B - Haute-Corse","21 - Côte-d'Or","22 - Côtes d'Armor","23 - Creuse","24 - Dordogne","25 - Doubs","26 - Drôme","27 - Eure","28 - Eure-et-Loir","29 - Finistère","30 - Gard","31 - Haute-Garonne","32 - Gers","33 - Gironde","34 - Hérault","35 - Ille-et-Vilaine","36 - Indre","37 - Indre-et-Loire","38 - Isère","39 - Jura","40 - Landes","41 - Loir-et-Cher","42 - Loire","43 - Haute-Loire","44 - Loire-Atlantique","45 - Loiret","46 - Lot","47 - Lot-et-Garonne","48 - Lozère","49 - Maine-et-Loire","50 - Manche","51 - Marne","52 - Haute-Marne","53 - Mayenne","54 - Meurthe-et-Moselle","55 - Meuse","56 - Morbihan","57 - Moselle","58 - Nièvre","59 - Nord","60 - Oise","61 - Orne","62 - Pas-de-Calais","63 - Puy-de-Dôme","64 - Pyrénées-Atlantiques","65 - Hautes-Pyrénées","66 - Pyrénées-Orientales","67 - Bas-Rhin","68 - Haut-Rhin","69 - Rhône","70 - Haute-Saône","71 - Saône-et-Loire","72 - Sarthe","73 - Savoie","74 - Haute-Savoie","75 - Paris","76 - Seine-Maritime","77 - Seine-et-Marne","78 - Yvelines","79 - Deux-Sèvres","80 - Somme","81 - Tarn","82 - Tarn-et-Garonne","83 - Var","84 - Vaucluse","85 - Vendée","86 - Vienne","87 - Haute-Vienne","88 - Vosges","89 - Yonne","90 - Territoire de Belfort","91 - Essonne","92 - Hauts-de-Seine","93 - Seine-St-Denis","94 - Val-de-Marne","95 - Val-D'Oise"],
              label: "Département" %>
    <%= f.input :description, label: "Description" %>
    <%= f.input :address,
      label: "Adresse",
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <%= f.input :price_per_day, label: 'Prix par jour' %>
    <%= f.input :number_of_bed, label: 'Nombre de lit' %>
    <%= f.input :smokers_welcome, label: 'Fumeur' %>
    <%= f.input :animals_welcome, label: 'Animaux bienvenus' %>
    <%= f.input :wifi, label: 'Wifi' %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, required: true, label: "Photos" %>
    <div class="create-castle-submit button-create">
        <input type="submit" name="commit" value="Ajouter" class="btn btn-create" data-disable-with="Create">
        <span></span>
    </div>
  <% end %>

  </div>
</div>

app/views/castles/_info_window.html.erb
<h2><%= link_to castle.name, castle_path(castle.id) %></h2>
<p><%= castle.address %></p>

app/views/castles/edit.html.erb
<%= link_to "Retour à l'annonce", castle_path %>

<p><%= render "form", castle: @castle %></p>

app/views/castles/index.html.erb
<% if params[:map] == 'true' %>

  <div style="width: 100%; height: 600px;" class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

    <% if @castles != nil %>
      <div class="link-to-map"><%= link_to "Voir la liste", castles_path %></div>
    <% end %>

<% else %>

  <div class="see-all">
    <% if policy(Castle).new? %>
      <%= link_to "Déposer une annonce", new_castle_path, class: "btn-new-castle"  %>
    <% end %>

    <% if params[:search].nil? %>
      <h2 class="title-index">Toutes les annonces</h2>
    <% else %>
      <% if @castles.empty? %>
        <h2 class="title-index"><%= "Pas de résultat pour '#{params[:search]}'" %></h2>
      <% else %>
        <h2 class="title-index">Résultats pour '<%= params[:search] %>'</h2>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <% @castles.each do |castle| %>

      <div class="col-4">

        <a href="<%= castle_path(castle.id)%>">
          <div class="card-product">
            <%= cl_image_tag castle.photos.first.key, height: 300, width: 400, crop: :fill %>

            <div class="card-product-infos">
              <% if castle.reviews.empty? %>
                <div class="rate">
                  <h2><%= castle.name %></h2>
                  <p>pas de note</p>
                </div>
              <% else %>
                <div class="rate">
                  <% reviews = castle.reviews.map do |r| p r.rating end %>
                  <h2 class="title-rate-card"><%= castle.name %></h2>
                  <p><%= reviews.sum / reviews.length %> /5 </p>
                </div>
              <% end %>
              <p><%= castle.department %></p>
              <p><%= castle.price_per_day %>€ / jour</p>
            </div>

          </div>
        </a>

      </div>

    <% end %>
  </div>

  <% if @castles != nil %>
    <div class="link-to-map"><%= link_to "Voir la carte", castles_path(map: true) %></div>
  <% end %>

<% end %>

app/views/castles/index_by_user.html.erb
<br>
<% user = User.where(id: params[:id])[0].first_name %>
<% vowel = ['a','e','i','o','u','y','A','E','I','O','U','Y'] %>
<% if vowel.include?(user[0])  %>
  <h1>Toutes les annonces d'<%= user %></h1>
<% else %>
  <h1>Toutes les annonces de <%= user %></h1>
<% end %>

<div class="row">
  <% @castles.each do |castle| %>
    <div class="col-4">
      <a href="<%= castle_path(castle.id)%>">

        <div class="card-product">
          <%= cl_image_tag castle.photos.first.key, height: 300, width: 400, crop: :fill %>

          <div class="card-product-infos">
              <% if castle.reviews.empty? %>
                <div class="rate">
                  <h2><%= castle.name %></h2>
                  <p>pas de note</p>
                </div>
              <% else %>
                <div class="rate">
                  <% reviews = castle.reviews.map do |r| p r.rating end %>
                  <h2 class="title-rate-card"><%= castle.name %></h2>
                  <p><%= reviews.sum / reviews.length %> /5 </p>
                </div>
              <% end %>
              <p><%= castle.department %></p>
              <p><%= castle.price_per_day %>€ / jour</p>
            </div>

        </div>

      </a>
    </div>
  <% end %>
</div>

app/views/castles/new.html.erb
<br>
<div class="secondary-button fs-5">
  <%= link_to "Retour", castles_path %>
</div>
<p><%= render "form", castle: @castle %></p>

app/views/castles/show.html.erb
<% if params[:map] == 'true' %>

  <div style="width: 100%; height: 600px;" class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

    <% if @castles != nil %>
      <div class="link-to-map"><%= link_to "Voir la liste", castles_path %></div>
    <% end %>

<% else %>

  <br>
  <!-- castle title and photos -->
  <div class="show-banner">

    <div class="more-info">
      <div>
        <h1><strong><%= @castle.name.capitalize %></strong></h1>
        <h4 class="text-muted"><%= @castle.subtitle %></h4>
      </div>
      <div>
        <p><i class="fa-solid fa-image"></i><%= link_to "  Toutes les photos", full_screen_path %></p>
        <br>
        <p><i class="fa-solid fa-map-location-dot"></i><%= link_to "  Voir sur la carte", castle_path(@castle, map: true) %></p>
        <br>
        <p><i class="fa-solid fa-comment-dots"></i><a href="#review">Laisser un commentaire</a></p>
      </div>
      <a href="#description" class="fa-solid fa-circle-arrow-down"></a>
    </div>

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
        <% @castle.photos.each_with_index do |photo, i|  %>
          <% break if i >= 3 %>
          <% if i == 0 %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
              <div class="div-img cover center w-100" style="background-image: url('<%= photo.url %>')"></div>
            </div>
        <% end %>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

  </div>


  <!-- castle booking checkout-->
  <div class="container p-3 mt-5">
    <div class="row">
      <div class="col-md-8 my-5">

        <h3 id="show-infos">Plus d'informations...</h3>


        <!-- card -->
        <div class="card px-5 py-4 mt-4">
          <% user = @castle.user.first_name %>
          <% vowel = ['a','e','i','o','u','y','A','E','I','O','U','Y'] %>
          <% if vowel.include?(user[0])  %>
            <p class="first-line"><em><%= link_to "Voir toutes les annonces d'#{@castle.user.first_name}", user_index_path(@castle.user.id) %></em>
          <% else %>
            <p class="first-line"><em><%= link_to "Voir toutes les annonces de #{@castle.user.first_name}", user_index_path(@castle.user.id) %></em>
          <% end %>

          <% if current_user != nil %>
            <% if Favorite.where(user_id: current_user.id, castle_id: @castle.id).empty? %>
              <%= link_to castle_favorites_path(@castle.id), data: {turbo_method: 'post'} do %>
                Ajouter aux favoris <i class="fa-regular fa-heart" style="color: grey; font-size: 20px;"></i></p>
              <% end %>
            <% else %>
              <%= link_to castle_favorite_path(@castle.id, Favorite.where(user_id: current_user.id, castle_id: @castle.id)[0].id), data: {turbo_method: 'delete'} do %>
                Supprimer des favoris <i class="fa-solid fa-heart" style="color: red; font-size: 20px;"></i></p>
              <% end %>
            <% end %>
          <% end %>

          <p><strong>Adresse : </strong><%= @castle.address %>, <%= @castle.department[5..50] %></p>
          <% if @castle.indexed %>
              <div class="indexed">
                <h6>Classé Monument Historique</h6>
                <img src="https://res.cloudinary.com/djyykxv2u/image/upload/v1659026036/castrvm/indexedMH_little_q2pngm.png" alt="">
              </div>
            <% end %>

          <p class="description" id="description"><%= @castle.description %></p><br>

          <div class="equipment">
            <% if @castle.smokers_welcome %>
              <p><i class="fa-solid fa-smoking fa-details" style="color: green; font-size: 20px;"></i>fumeurs bienvenus</p>
            <% else %>
              <p><i class="fa-solid fa-smoking fa-details" style="color: red; font-size: 20px;"></i>interdit de fumer</p>
            <% end %>
            <% if @castle.animals_welcome %>
              <p><i class="fa-solid fa-paw fa-details" style="color: green; font-size: 20px;"></i>animaux bienvenus</p>
            <% else %>
              <p><i class="fa-solid fa-paw fa-details" style="color: red; font-size: 20px;"></i>animaux interdits</p>
            <% end %>
            <% if @castle.wifi %>
              <p><i class="fa-solid fa-wifi fa-details" style="color: green;"></i>wifi disponible</p>
            <% else %>
              <p><i class="fa-solid fa-wifi fa-details" style="color: red;"></i>wifi indisponible</p>
            <% end %>
            <p><i class="fa-solid fa-bed fa-details" style="color: green;"></i><%= @castle.number_of_bed %> lits disponibles</p>
          </div>
        </div>

        <div class="edit-destroy">
            <% if policy(@castle).edit? %>
              <button class="btn-edit">
                <a class="fa-solid fa-pen-to-square">
                <%= link_to "Modifiez l'annonce", edit_castle_path(@castle), class: "edit" %></a>
              </button>
            <% end %>
          </a>
          <br>
          <% if policy(@castle).destroy? %>
            <%= link_to "Supprimez l'annonce", castle_path(@castle), data: {turbo_method: "delete"}, class: "destroy", onClick:'Confirm()' %></a>
          <% end %>
        </div>

        <script language='javascript'>
          function Confirm() {
            if (confirm("Etes-vous sûr ?")) {
              formulaire.submit();
            }
          }
        </script>

        <% if !@castle.reviews.empty? %>
          <div class="reviews">
            <% @castle.reviews.each do |r| %>
              <div class="review">
                <div class="review-infos">
                  <p>Commentaire laissé par <strong><%= User.where(id: r.user_id).first.first_name %> <%= User.where(id: r.user_id).first.last_name[0].capitalize %></strong> le <%= r.created_at.strftime('%d/%m/%Y') %> à <%= r.created_at.strftime('%H:%M:%S') %></p>
                  <% if r.reference.empty? %>
                    <p class="unverified"><strong>réservation non vérifiée</strong></p>
                  <% else %>
                    <p class="verified"><strong>réservation vérifiée</strong></p>
                  <% end %>
                </div>
                <% if r.rating == 0 %>
                  <p>Note : <em>aucune étoile</em></p>
                <% elsif r.rating == 1 %>
                  <p>Note : <i class="fa-solid fa-star"></i></p>
                <% elsif r.rating == 2 %>
                  <p>Note : <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
                <% elsif r.rating == 3 %>
                  <p>Note : <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
                <% elsif r.rating == 4 %>
                  <p>Note : <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
                <% else %>
                  <p>Note : <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></p>
                <% end %>
                <hr>
                <p><%= r.content %></p>
                <% if current_user != nil && current_user.id == r.user_id %>
                  <div class="edit">
                    <%= link_to "Modifier votre commentaire", edit_review_path(r.id) %>
                    <%= link_to "Supprimer commentaire", review_path(r.id), data: {turbo_method: "delete"} %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="create-review" id="review">
          <h3>Laissez un commentaire</h3>
          <%= simple_form_for [@castle, @review] do |f| %>
            <%= f.input :reference, label: "Référence de votre location (votre commentaire apparaîtra comme validé)" %>
            <%= f.input :content, label: "Votre commentaire" %>
            <%= f.input :rating, collection: 0..5, label: "Note"  %>
            <div class="create-castle-submit button-create">
              <input type="submit" name="commit" value="Ajouter" class="btn btn-create" data-disable-with="Create">
              <span></span>
            </div>
          <% end %>
        </div>

      </div>

      <div class="col-md-4 ">
        <!-- checkout -->
        <div class="card p-3 mt-1  container-booking">

          <!-- make this a full length button -->
          <div class="row ">
            <div class="d-flex justify-content-between bd-highlight mt-2">
              <div class="bd-highlight">
                <p><strong><%= @castle.price_per_day %> €</strong> /jour</p>
              </div>
            </div>

            <div class="all checkout form-book" data-controller="dynamic-booking-price"
                      data-dynamic-booking-price-night-value="<%= @castle.price_per_day %>">
                <div class="fields-book-form d-flex text-muted justify-content-center">

                  <%= simple_form_for [@castle, @booking],
                  html: {
                    data: {
                      controller: 'flatpickr'
                    }
                  } do |f| %>
                    <div class="flex-grow-1 bd-highlight d-flex mx-auto ">
                      <%= f.input :start_date,
                      as: :string,
                      label: "Date de début",
                      input_html: {
                        data:
                        {
                          flatpickr_target: 'startDateInput',
                          dynamic_booking_price_target: 'startDateInput',
                          action: 'change->dynamic-booking-price#update'
                        }
                      } %>
                    </div>
                    <div class="flex-shrink-1 bd-highlight border-left d-flex mx-auto">
                      <%= f.input :end_date,
                      as: :string,
                      label: "Date de fin",
                      input_html: {
                        data: {
                          flatpickr_target: 'endDateInput',
                          dynamic_booking_price_target: 'endDateInput',
                          action: 'change->dynamic-booking-price#update'
                        }
                      } %>
                    </div>
                    <div><%= f.input :number_of_guest, label: "Nombre d'hôtes" %></div>
                  <div class=" mt-4 button-booking">
                    <input type="submit" name="commit" value="Je réserve"  data-disable-with="Book it" class="sup-button-booking">
                    <span></span>
                  </div>
                </div>

                <div class="d-flex justify-content-between bd-highlight">
                  <div class="p-2 bd-highlight">
                    <p><strong>Total</strong></p>
                  </div>
                  <div class="p-2 bd-highlight">
                    <p> <span data-dynamic-booking-price-target="priceHolder"></span> €</p>
                  </div>
                </div>

                <div class="d-flex justify-content-between bd-highlight">
                  <div class="p-2 bd-highlight">
                    <p><strong>Frais de ménage</strong></p>
                  </div>
                  <div class="p-2 bd-highlight">
                    <p>50 €</p>
                  </div>
                </div>

                <div class="d-flex justify-content-between bd-highlight">
                  <div class="p-2 bd-highlight">
                    <p><strong>Taxe de séjour</strong></p>
                  </div>
                  <div class="p-2 bd-highlight">
                    <p>2 €</p>
                  </div>
                </div>

                <div class="d-flex justify-content-between bd-highlight border-top">
                  <div class="p-2 bd-highlight">
                    <p><strong>Total</strong> TTC</p>
                  </div>
                  <div class="p-2 bd-highlight">
                    <p><strong><span data-dynamic-booking-price-target="totalPriceHolder"></span> €</strong></p>
                  </div>
                </div>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap JavaScript library -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <br>
<% end %>